### PR TITLE
Get full note title when many periods in filename

### LINKED ISSUE #10: Plaintext converter: Note title of input .txt with period in filename truncated
Using the Plaintext converter, filenames of .txt files containing periods are truncated after the first period in the output Standard Notes note title. 

E.g. input with filename "first.second.txt" -> Standard Note title "first".

### PR DESCRIPTION
**Pull request by winged-pegasus**
Closes #10

### CODE REVIEW

**Comment by atmoio** [comment]
Thanks! Note however that I don't think this package is used anywhere anymore. The web app conversion logic lives directly in the app repo.

**Comment by winged-pegasus** [comment]
Okay, thanks.

I will make the MR there, for this fix as well, if possible.

------- Original Message -------

**Comment by winged-pegasus** [comment]
Can you confirm what repo is being hosted/used for https://standardnotes.com/tools I can't find any references to the text and it had that error that I fixed, while it appears that the import tool embedded in the app doesn't have the same issue of multiple periods in file names

------- Original Message -------

**Comment by atmoio** [comment]
Oh the website is still using sntools, but actually that page should have been taken down, as the web app/desktop does conversions now directly when you click on the Import option:

Screenshot 2023-05-30 at 11 16 12 AM

**Pull request merged**
